sfCombineJs:
  url:  /js-min/*
  param:
    module: sfCombine
    action: js

sfCombineCss:
  url:  /css-min/*
  param:
    module: sfCombine
    action: css
  
sfCombine:
  url:  /sfCombine/:action/*